# apiVersion: v1
# kind: Namespace
# metadata:
#   annotations:
#     openshift.io/description: ""
#     openshift.io/display-name: Nexus Registry
#     openshift.io/sa.scc.mcs: s0:c24,c14
#     openshift.io/sa.scc.supplemental-groups: 1000580000/10000
#     openshift.io/sa.scc.uid-range: 1000580000/10000
#   name: sonarqube
# spec:
#   finalizers:
#   - kubernetes
# ---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-dep
  namespace: sonarqube
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9.6.17
          # resources:
          #   limits:
          #     memory: "1Gi"
          #     cpu: "1"
          #   requests:
          #     memory: "1Gi"
          #     cpu: "500m"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: sonarqube
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

