apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonarqube-dep
  namespace: sonarqube
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarqube
        tuned.openshift.io/elasticsearch: "true"
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:community
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /about
              port: 9000
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            limits:
              memory: "3Gi"
              cpu: "2"
            requests:
              memory: "2Gi"
              cpu: "1"
          envFrom:
            - configMapRef:
                name: sonarqube-config
          volumeMounts:
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data
      volumes:
      - name: sonarqube-data
        persistentVolumeClaim:
          claimName: sonarqube-pvc

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-pvc
  namespace: sonarqube
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

