apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
  labels:
    app: sonarqube
spec:
  replicas: 1
  # selector: 
  #   app: sonarqube
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarqube
        tuned.openshift.io/elasticsearch: "true"
    spec:
      containers:
      - name: sonarqube
        ports:
        - containerPort: 9000
          protocol: TCP 
        image: quay.io/gpte-devops-automation/sonarqube:7.9.1 #sonarqube:community
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /about
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /about
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: "3Gi"
            cpu: "2"
          requests:
            memory: "2Gi"
            cpu: "1"
        envFrom:
          - configMapRef:
              name: sonarqube-env
        volumeMounts:
          - name: sonarqube-data
            mountPath: /opt/sonarqube/data
      volumes:
      - name: sonarqube-data
        persistentVolumeClaim:
          claimName: sonarqube-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-pvc
  namespace: sonarqube
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

