# kubectl label nodes linux1 role=ingress
# kubectl get nodes --show-labels
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress-sa
  namespace: nginx-ingress
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: nginx-ingress
  labels:
    app: nginx-ingress
data:
  use-proxy-protocol: "false"
  body-size: "0"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: nginx-ingress
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services
  namespace: nginx-ingress
---