apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: Local Password
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpasswd
  - name: IdM RedCloud
    challenge: true
    login: true
    mappingMethod: claim
    type: LDAP
    ldap:
      attributes:
        id:
        - dn
        email:
        - mail
        name:
        - cn
        preferredUsername:
        - uid
      bindDN: "uid=admin,cn=users,cn=accounts,dc=redcloud,dc=land"
      bindPassword:
        name: idm-bind-password
      insecure: false
      ca:
        name: idm-tls-ca
      url: "ldap://idm.redcloud.land/cn=users,cn=accounts,dc=redcloud,dc=land?uid"