apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: IdM
    mappingMethod: claim
    type: LDAP
    ldap:
      attributes:
        id:
        - dn
        email:
        - mail
        name:
        - cn
        preferredUsername:
        - uid
      bindDN: "uid=ocp-service-account,cn=users,cn=accounts,dc=shaker242,dc=lab"
      bindPassword:
        name: ldap-secret
      ca:
        name: ca-config-map
      insecure: false
      url: "ldap://ldap.shaker242.lab/cn=users,cn=accounts,dc=shaker242,dc=lab?uid"
# ---
# kind: LDAPSyncConfig
# apiVersion: v1
# url: ldap://ldap.shaker242.lab:389
# bindDN: uid=ocp-service-account,cn=users,cn=accounts,dc=shaker242,dc=lab
# bindPassword:
#   name: ldap-secret
# insecure: false
# rfc2307:
#     groupsQuery:
#         baseDN: "cn=groups,cn=accounts,dc=shaker242,dc=lab"
#         scope: sub
#         derefAliases: never
#         pageSize: 0
#         filter: (objectclass=groupOfNames)
#     groupUIDAttribute: dn
#     groupNameAttributes: [ cn ]
#     groupMembershipAttributes: [ member ]
#     usersQuery:
#         baseDN: "cn=users,cn=accounts,dc=shaker242,dc=lab"
#         scope: sub
#         derefAliases: never
#         pageSize: 0
#     userUIDAttribute: dn
#     userNameAttributes: [ uid ]
#     tolerateMemberNotFoundErrors: false
#     tolerateMemberOutOfScopeErrors: false