# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: image-registry-pv
# spec:
#   accessModes:
#     - ReadWriteMany
#   capacity:
#     storage: 100Gi
#   nfs:
#     path: /registry
#     server: 172.16.1.120
#   persistentVolumeReclaimPolicy: Retain

---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "image-registry-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeMode: Filesystem



# add the name of your PVC: "oc edit configs.imageregistry.operator.openshift.io -o yaml"
# leave "claim" empty to auto-assign pvc name to pv.
#
# storage:
#   pvc:
#     claim: 
#
# /registry *(rw,sync,no_wdelay,no_root_squash,insecure,fsid=0)
#


