AUTHENTICATION_TYPE: LDAP


DISTRIBUTED_STORAGE_CONFIG:
  default:
  - RHOCSStorage
  - access_key: rRVYOTpBqZ1W9cXBTOWd
    bucket_name: quaystore
    hostname: s3.openshift-storage.svc
    is_secure: true
    port: '443'
    secret_key: ztOia2nmwFxvllAS4dnclBTFIoTeXaR6lGdPu7qF
    storage_path: /datastorage/registry
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []


LDAP_ADMIN_DN: uid=admin,cn=users,cn=accounts,dc=redcloud,dc=land
LDAP_ADMIN_PASSWD: J5rdfv5e4!
LDAP_BASE_DN:
- dc=redcloud
- dc=land
LDAP_EMAIL_ATTR: mail
LDAP_UID_ATTR: uid
LDAP_URI: ldap://idm.redcloud.land
LDAP_USER_RDN:
- cn=users
- cn=accounts
