# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: jenkins-pvc
#   namespace: jenkins
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
#   storageClassName: managed-nfs-storage