kind: Service
apiVersion: v1
metadata:
    name: jenkins-master
    namespace: jenkins
spec:
    selector:
        app: jenkins-master
    ports:
        - port: 50000
          protocol: TCP
          targetPort: 50000
          name: slaves
        - port: 80
          protocol: TCP
          targetPort: 8080
          name: ui