apiVersion: apps/v1
kind: Deployment
metadata:
 name: jenkins-master
 namespace: jenkins
spec:
 replicas: 1
 selector:
  matchLabels:
    app: jenkins-master
 template:
  metadata:
   labels:
    app: jenkins-master
  #  annotations:
  #   seccomp.security.alpha.kubernetes.io/pod: docker/default
  spec:
   serviceAccountName: jenkins-service-account
   containers:
   - name: master
     image: shaker242/jenkins:43
     securityContext:
       allowPrivilegeEscalation: false
     ports:
     - containerPort: 8080
     - containerPort: 5000
     readinessProbe:
      # httpGet:
      #  path: /login
      #  port: 8080
      # periodSeconds: 10
      # timeoutSeconds: 5
      # successThreshold: 2
      # failureThreshold: 5
     volumeMounts:
     - mountPath: /var/jenkins_home
       name: jenkins
    #  - mountPath: /usr/bin/crio
    #    name: crio
    #  - mountPath: /usr/bin/kubectl
    #    name: kubectl
    #  - mountPath: /var/run/crio/crio.sock
    #    name: crio-sock
     resources:
      limits:
       cpu: 500m
       memory: 1500Mi
      requests:
       cpu: 500m
       memory: 1500Mi
   volumes:
   - name: jenkins
     persistentVolumeClaim:
      claimName: jenkins-pvc
  #  - name: kubectl
  #    hostPath:
  #     path: /usr/bin/kubectl
  #     type: File
  #  - name: crio
  #    hostPath:
  #     path: /usr/bin/crio
  #     type: File
  #  - name: crio-sock
  #    hostPath:
  #     path: /var/run/crio/crio.sock
      # type: Socket
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-nfs-storage