apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv1
  namespace: jenkins
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs/jenkins_home
    server: 172.16.1.5

