kind: Pod
apiVersion: v1
metadata:
  name: secret-test-pod
  namespace: jenkins
  labels:
    name: secret-test
  annotations:
   seccomp.security.alpha.kubernetes.io/pod: docker/default
spec:
  containers:
  - name: test-container
    image: dtr.olly.dtcntr.net/admin/jenkins-slave:0.5
    volumeMounts:
    - name: docker-sock-volume
      mountPath: "/var/run/docker.sock"
    - name: ucp-key
      mountPath: "/home/jenkins"
      readOnly: true
    env:
    - name: NOTARY_DELEGATION_PASSPHRASE
      valueFrom:
        secretKeyRef:
          name: notary-passphrases
          key: delegation-passphrase
    - name: DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE
      valueFrom:
        secretKeyRef:
          name: notary-passphrases
          key: delegation-passphrase
  volumes:
  - name: docker-sock-volume
    hostPath:
      path: /var/run/docker.sock
  - name: ucp-key
    secret:
      secretName: ucp-key
