- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install a list of packages
  apt:
    pkg:
    - chrony
    - nfs-common
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg-agent 

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
