apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: ceph-bucket
  namespace: rook-ceph
spec:
  bucketName:
  generateBucketName: nexus-store
  storageClassName: rook-ceph-bucket
  additionalConfig: