# apiVersion: "k8s.cni.cncf.io/v1"
# kind: NetworkAttachmentDefinition
# metadata:
#   name: macvlan-network
# spec:
#   config: '{
#     "cniVersion": "0.3.1",
#     "name": "bridge-network",
#     "master": "ens224",
#     "type": "macvlan",
#     "isGateway": true,
#       "ipam": {
#         "type": "host-local",
#         "subnet": "192.168.11.0/24",
#         "rangeStart": "192.168.11.221",
#         "rangeEnd": "192.168.11.230",
#         "routes": [
#           { "dst": "0.0.0.0/0" }
#         ],
#         "gateway": "192.168.11.1"
#     }
# }'
# # does not work for kubevirt
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-network
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "macvlan-network",
    "type": "macvlan",
    "master": "ens224",
    "mode": "bridge",
    "isGateway": true,
    "ipam": {
     "type": "host-local",
     "subnet": "192.168.11.0/24",
     "dataDir": "/mnt/cluster-ipam"
    }
}'
