apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv 
spec:
  capacity:
    storage: 100Gi 
  accessModes:
    - ReadWriteOnce 
  rbd: 
    monitors: 
      #- 192.168.122.133:6789
      - 172.16.1.23:6789 
    pool: rbd
    image: ceph-image
    user: admin
    secretRef:
      name: ceph-secret 
    fsType: ext4 
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
