apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  dashboard:
    enabled: true
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
    - name: "linux1"
      devices:
      - name: "sdb"
    - name: "linux2"
      devices:
      - name: "sdb"
    - name: "linux3"
      devices:
      - name: "sdb"
    - name: "linux4"
      devices:
      - name: "sdb"
    