apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: auto-nfs
  annotations:
  # storageclass.kubernetes.io/is-default-class: "true"
provisioner: fuseim.pri/ifs
# Since this is a lab envirnment, if the project / namespace / pvc is removed 
# then also remove the dynamicly created volume instead of archiving it and wasting
# needed nfs disk space.
parameters:
  archiveOnDelete: "false" 