apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "localstorage-ocs-osd"
  namespace: "openshift-storage"
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - linux0
            - linux1
            - linux2
  storageClassDevices:
    - storageClassName: "localstorage-ocs-osd-sc"
      volumeMode: Block 
      devicePaths:
        - /dev/sdb
