## edit the deployments rook-ceph-mds-storagecluster-cephfilesystem-a & rook-ceph-mds-storagecluster-cephfilesystem-b
## to set the cpu request to =1


apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  namespace: openshift-storage
  name: storagecluster
spec:
  resources:
    mds:
      limits:
        cpu: 3
      requests:
        cpu: 1
  manageNodes: false
  monPVCTemplate:
    spec:
      storageClassName: localstorage-ocs-mon-sc
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  storageDeviceSets:
  - name: deviceset
    count: 3
    resources: {}
    placement: {}
    dataPVCTemplate:
      spec:
        storageClassName: localstorage-ocs-osd-sc
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: 500Gi 
    portable: true
