apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-service-account
      containers:
      - name: jenkins
        image: jenkins/jenkins
        # livenessProbe:
        #   failureThreshold: 2
        #   httpGet:
        #     path: /login
        #     port: 8080
        #     scheme: HTTP
        #   initialDelaySeconds: 420
        #   periodSeconds: 360
        #   successThreshold: 1
        #   timeoutSeconds: 240
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /login
        #     port: 8080
        #     scheme: HTTP
        #   initialDelaySeconds: 3
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 240
        resources:
          limits:
            memory: 2Gi
        securityContext:
          capabilities: {}
          privileged: false
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-data
      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: jenkins-data