apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  type: NodePort 
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30080
    name: http
  - port: 443
    protocol: TCP
    nodePort: 30443
    name: https
  selector:
    app: nginx-ingress