apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quay-ecosystem
  namespace: quay-enterprise
spec:
  quay:
    externalAccess: 
      hostname: quay.redcloud.land
      configHostname: quayconfig.apps.openshift.redcloud.land
      tls:
        secretName: custom-quay-ssl
        termination: passthrough
    keepConfigDeployment: true
    imagePullSecretName: redhat-pull-secret
    database:
      volumeSize: 10Gi
    configFiles:
      - secretName: ca-redcloud
        files:
          - key: ca.crt
            type: extraCaCert
  clair:
    enabled: true
    imagePullSecretName: redhat-pull-secret
    configFiles:
      - secretName: ca-redcloud
        files:
          - key: ca.crt
            type: extraCaCert