apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quay-ecosystem
spec:
  quay:
    keepConfigDeployment: true
    hostname: quay.redcloud.land
    configHostname: quayconfig.apps.openshift.redcloud.land
    imagePullSecretName: redhat-pull-secret
    sslCertificatesSecretName: custom-quay-ssl
    database:
      volumeSize: 10Gi
    configFiles:
      - secretName: ca-redcloud
        files:
          - key: ca.crt
            type: extraCaCert
  clair:
    enabled: true
    imagePullSecretName: redhat-pull-secret
    updateInterval: "60m"