# apiVersion: v1
# kind: Namespace
# metadata:
#   annotations:
#     openshift.io/description: ""
#     openshift.io/display-name: Nexus Registry
#     openshift.io/sa.scc.mcs: s0:c24,c14
#     openshift.io/sa.scc.supplemental-groups: 1000580000/10000
#     openshift.io/sa.scc.uid-range: 1000580000/10000
#   name: nexus
# spec:
#   finalizers:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: docker.io/sonatype/nexus3
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
            requests:
              memory: "1Gi"
              cpu: "500m"
          # readinessProbe:
          #   tcpSocket:
          #     port: 8081
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   tcpSocket:
          #     port: 8081
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
          #   periodSeconds: 3
          ports:
            - containerPort: 8081 # web
            - containerPort: 5000 # docker
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-rbd
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nexus-rbd
  namespace: nexus
  annotations:
    volume.beta.kubernetes.io/storage-class: "storagecluster-ceph-rbd"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

