apiVersion: v1
kind: Service
metadata:
  name: nexus-svc
  namespace: nexus
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8081'
spec:
  selector: 
    app: nexus
  type: NodePort  
  ports:
    - port: 8081
      targetPort: 8081
      name: ui
    - port: 5000
      targetPort: 5000
      name: docker

# ---
# apiVersion: route.openshift.io/v1
# kind: Route
# metadata:
#   labels:
#     app: nexus
#   name: nexus
#   namespace: nexus
# spec:
#   host: nexus.redcloud.land
#   port:
#     targetPort: 8081
#   to:
#     kind: Service
#     name: nexus-svc
#   tls:
#     secretName: nexus-tls 
#     insecureEdgeTerminationPolicy: Redirect
#     termination: edge