- name: Add Docker's official apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_key
  ignore_errors: true

- name: Add Docker apt key
  shell: curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  args:
    warn: no

- name: Add Docker stable repository.
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update for Docker repo
  apt:
    update_cache: yes

- name: Install latest docker packages
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Make sure a service is running
  systemd:
    state: started
    name: docker
