apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: quay
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: quay
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: quay
subjects:
- kind: ServiceAccount
  name: default