AUTHENTICATION_TYPE: LDAP
BITTORRENT_FILENAME_PEPPER: 2ed12cca-7663-4bbb-bf81-1b63fa116ff4
BUILDLOGS_REDIS:
  host: quay-ecosystem-redis
  port: 6379
DATABASE_SECRET_KEY: '64418585637946663569238785172867083059933536781941874981443945716352137452767'
DB_URI: postgresql://quay:quay@quay-ecosystem-quay-postgresql/quay
DEFAULT_TAG_EXPIRATION: 2w
DISTRIBUTED_STORAGE_CONFIG:
  default:
  - RHOCSStorage
  - access_key: rRVYOTpBqZ1W9cXBTOWd
    bucket_name: quaystore
    hostname: s3.openshift-storage.svc
    is_secure: true
    port: '443'
    secret_key: ztOia2nmwFxvllAS4dnclBTFIoTeXaR6lGdPu7qF
    storage_path: /datastorage/registry
DISTRIBUTED_STORAGE_PREFERENCE:
- default
ENTERPRISE_LOGO_URL: /static/img/quay-horizontal-color.svg
FEATURE_ACI_CONVERSION: false
FEATURE_ANONYMOUS_ACCESS: true
FEATURE_APP_REGISTRY: false
FEATURE_APP_SPECIFIC_TOKENS: true
FEATURE_BUILD_SUPPORT: false
FEATURE_CHANGE_TAG_EXPIRATION: true
FEATURE_DIRECT_LOGIN: true
FEATURE_MAILING: false
FEATURE_PARTIAL_USER_AUTOCOMPLETE: true
FEATURE_REPO_MIRROR: false
FEATURE_REQUIRE_TEAM_INVITE: true
FEATURE_RESTRICTED_V1_PUSH: true
FEATURE_SECURITY_NOTIFICATIONS: true
FEATURE_SECURITY_SCANNER: true
FEATURE_STORAGE_REPLICATION: false
FEATURE_USERNAME_CONFIRMATION: true
FEATURE_USER_CREATION: true
FEATURE_USER_LOG_ACCESS: true
GPG2_PRIVATE_KEY_FILENAME: signing-private.gpg
GPG2_PUBLIC_KEY_FILENAME: signing-public.gpg
LDAP_ADMIN_DN: uid=admin,cn=users,cn=accounts,dc=redcloud,dc=land
LDAP_ADMIN_PASSWD: J5rdfv5e4!
LDAP_BASE_DN:
- dc=redcloud
- dc=land
LDAP_EMAIL_ATTR: mail
LDAP_UID_ATTR: uid
LDAP_URI: ldap://idm.redcloud.land
LDAP_USER_RDN:
- cn=users
- cn=accounts
LOG_ARCHIVE_LOCATION: default
MAIL_DEFAULT_SENDER: support@quay.io
MAIL_PORT: 587
MAIL_USE_TLS: true
PREFERRED_URL_SCHEME: https
REGISTRY_TITLE: Red Hat Quay
REGISTRY_TITLE_SHORT: Red Hat Quay
REPO_MIRROR_SERVER_HOSTNAME: null
REPO_MIRROR_TLS_VERIFY: false
SECRET_KEY: '67059347806345933572570185303367434147422716368767903213877927551487818922590'
SECURITY_SCANNER_ENDPOINT: https://quay-ecosystem-clair.quay-enterprise.svc:6060
SECURITY_SCANNER_ISSUER_NAME: security_scanner
SERVER_HOSTNAME: quay.redcloud.land
SETUP_COMPLETE: true
SIGNING_ENGINE: gpg2
SUPER_USERS:
- quay
TAG_EXPIRATION_OPTIONS:
- 0s
- 1d
- 1w
- 2w
- 4w
TEAM_RESYNC_STALE_TIME: 60m
TESTING: false
USERFILES_LOCATION: default
USERFILES_PATH: userfiles/
USER_EVENTS_REDIS:
  host: quay-ecosystem-redis
  port: 6379
USE_CDN: false
V3_UPGRADE_MODE: complete
