apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: jenkins-master
    namespace: jenkins
  spec:
    ports:
    - name: port-1
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: port-2
      port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      app: jenkins-master
    sessionAffinity: None
    type: ClusterIP
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""