apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: jenkins-tls
  namespace: jenkins
spec:
  host: jenkins.shaker242.lab
  port:
    targetPort: port-1
  tls:
    caCertificate: |-
      -----BEGIN CERTIFICATE-----
      MIIEkTCCAvmgAwIBAgIBATANBgkqhkiG9w0BAQsFADA4MRYwFAYDVQQKDA1TSEFL
      RVIyNDIuTEFCMR4wHAYDVQQDDBVDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMjAw
      MjA3MTUyNTAxWhcNNDAwMjA3MTUyNTAxWjA4MRYwFAYDVQQKDA1TSEFLRVIyNDIu
      TEFCMR4wHAYDVQQDDBVDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwggGiMA0GCSqGSIb3
      DQEBAQUAA4IBjwAwggGKAoIBgQCtd6hWCCSGDEwFZ6ZVEZdcixl47PhJLToFjIXL
      IYyvVFrgzJNuR5tLU1SDUbE8A0wTLqXyiLK+m5DI7hPYrFi0dajsezLECn2LwqOd
      gNX9kV/uM3tKlzvsE5AukjUEqSul15KGOAwzMqc8t8BzCo8UxexLMlStk25YzLgY
      9FcH6Cfb++0dp3x/zUaXgpBBO/2M1kgWV5wXcmwYuSdPCS8S8F6D/VpTKCFXSUB6
      yLg/dXKL0JWGKzy2vDMxeMdZ6Gy+AS0nk44uOdE0jvI+eoXdh2SACIlxLERq7/rG
      JRiA/8xnZMoeI0DxIGEDT5BHa5lY0wKKmW1bkpvkGu6F/DfpH0LYTHnSlu3CPWSa
      UuO5Km1ZCAknx1xL7N2M/1+1/AJp/R8bJ+EdNfCBVAHSLfTiY2Xo1Ze+bxDNx1A3
      Bjjw70V21Zfo6YhQz3Ia/F9v9xoy9Aj4vRMDQVysZVDd+HdjzP9L2mCTbDQj2soF
      /edyvqFf2QDYRMMcgEZn6WttEucCAwEAAaOBpTCBojAfBgNVHSMEGDAWgBREGBxi
      xGqHEFeJnbXouhYKmECnrjAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIB
      xjAdBgNVHQ4EFgQURBgcYsRqhxBXiZ216LoWCphAp64wPwYIKwYBBQUHAQEEMzAx
      MC8GCCsGAQUFBzABhiNodHRwOi8vaXBhLWNhLnNoYWtlcjI0Mi5sYWIvY2Evb2Nz
      cDANBgkqhkiG9w0BAQsFAAOCAYEAcTsrv16Vw2Ez229FNwd2Gga1fcD18y62XwhR
      Mq9tCl/Ic8nPZCg60MioedNg2JJ7UATDFqzLQnd+X+VvNK8V1iHyhxc130NcJveZ
      KHqCvwfYr5zPpOXJNxe+a2CnojnIvlgygV6Uk8T/EhtjusRNI6vuhI7C+MZ3XJoq
      Uht1U3LWjnI2IrjKGvEsd3LCRs8nKkXGCIXBA16HbDldpJgVHX2MeLk7QpgNK5gU
      BrJ9N1pwRekJ630R3hkau4RJlPJ1WzdBYSs233iPDnTQuMyLkaTY6x1EHsrBa/+R
      xqJ8MLYu2hKZCNi5XijwQVqVS0znSlu/J/PEUyp0m/CBnzVt+IvJvKHHRs4JhF0d
      7+0XGrXixHskbjtHN/S+LIWtKVXA3juRP3TCOOLGkr3+WsFU9KV9IK/xSBPue/HN
      DTY42qVrGQvTzd5pFIJa3qo70WlQlcuEtz+Atc7L8UCNuFPGJW4M5GD2fCx5KPGu
      rx1ctNkUzFKXiNUCx2io0bYVua42
      -----END CERTIFICATE-----
    certificate: "-----BEGIN CERTIFICATE-----\r\nMIIEvTCCAyWgAwIBAgIBFDANBgkqhkiG9w0BAQsFADA4MRYwFAYDVQQKDA1TSEFL\r\nRVIyNDIuTEFCMR4wHAYDVQQDDBVDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMjAw\r\nMzIwMTUwOTAwWhcNMjIwMzIxMTUwOTAwWjA4MRYwFAYDVQQKDA1TSEFLRVIyNDIu\r\nTEFCMR4wHAYDVQQDDBVqZW5raW5zLnNoYWtlcjI0Mi5sYWIwggEiMA0GCSqGSIb3\r\nDQEBAQUAA4IBDwAwggEKAoIBAQDCp6UKee8S3e6Y3ZSu1NEFT/vyX7T2A/dyYpio\r\nwj2Z344D/VL4qyu1iMWaxKBlMQrlcAXj4p5EbB/JFjwEoeAny3ChGOd1GjkhZvVG\r\nfD6ZIm33/hCyj+F5ybTKOqDEDv7Kq41zOiAL5e7DZJiGQunqRJgJnJK+iLe2rLTf\r\nJUBbvLEYGbDyIHrajPYs5Wk8Z8vpls2l50bpHx72xGSLWEWdKTq2cE8DtR25cvD4\r\nWa1RJlVaaJdQ2T0zuNEY9Vkg1gc9buoXq8P8+gj1xqoaB6S/YzTY+2mb85mLN32k\r\ndjO44ERPNsBgYhiPSj3Hr3jL2Ou+rCwqAvLHmPA4EuSGWD1PAgMBAAGjggFQMIIB\r\nTDAfBgNVHSMEGDAWgBREGBxixGqHEFeJnbXouhYKmECnrjA/BggrBgEFBQcBAQQz\r\nMDEwLwYIKwYBBQUHMAGGI2h0dHA6Ly9pcGEtY2Euc2hha2VyMjQyLmxhYi9jYS9v\r\nY3NwMA4GA1UdDwEB/wQEAwIE8DAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH\r\nAwIweAYDVR0fBHEwbzBtoDWgM4YxaHR0cDovL2lwYS1jYS5zaGFrZXIyNDIubGFi\r\nL2lwYS9jcmwvTWFzdGVyQ1JMLmJpbqI0pDIwMDEOMAwGA1UECgwFaXBhY2ExHjAc\r\nBgNVBAMMFUNlcnRpZmljYXRlIEF1dGhvcml0eTAdBgNVHQ4EFgQUltkncRaZHg/W\r\nkp4ptPu6WuVgQKEwIAYDVR0RBBkwF4IVamVua2lucy5zaGFrZXIyNDIubGFiMA0G\r\nCSqGSIb3DQEBCwUAA4IBgQAxgpcaV0vBhuOAgk6UumV0H8nJ25MQOXqiUEee5xpp\r\nep4jHOVWTGcAie3uCfR4Xidrsraldk6lylIRdWM1l94z3vLCvCLjZPnBkigUptAM\r\n5YWclfHcgegZJamODhaeoqbdPoTqnVunIuAHuo6SqMXv8tUx6ELAALSHATnf1bS4\r\nO5LBmS1yAwcEblnb2AxqeLJfr7H8rrJjgBs4nMIdkkQSJ1kAbEuZJEuvBrQcVJPi\r\nhaXmh4TpheM1h0hJkBx1cnWn9L0VznI/U10J8VHxjiwevXeDGMYugGHda7qD+EeI\r\nMtsDzCCKMkR9TRM6XgWeH5MvoZGgBnRYRwTr4xhMI29zDDCtlDLMcQFN9tUGlPh0\r\nmEsN15ly0HQAz+zlr89yNkvB0qzhK9NUd/0fgtrCiW0M7XGctNHID2rtfwfY/btP\r\n5nFMBRSBHITsMwUt0yB2lrGgBtwCgu0uKUZVMrm1V0dIlUAJ1QNadCBO8+t0mvbI\r\nDEIE65QbKsr7d4gD7/52gCs=\r\n-----END
      CERTIFICATE-----"
    insecureEdgeTerminationPolicy: Redirect
    key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDCp6UKee8S3e6Y
      3ZSu1NEFT/vyX7T2A/dyYpiowj2Z344D/VL4qyu1iMWaxKBlMQrlcAXj4p5EbB/J
      FjwEoeAny3ChGOd1GjkhZvVGfD6ZIm33/hCyj+F5ybTKOqDEDv7Kq41zOiAL5e7D
      ZJiGQunqRJgJnJK+iLe2rLTfJUBbvLEYGbDyIHrajPYs5Wk8Z8vpls2l50bpHx72
      xGSLWEWdKTq2cE8DtR25cvD4Wa1RJlVaaJdQ2T0zuNEY9Vkg1gc9buoXq8P8+gj1
      xqoaB6S/YzTY+2mb85mLN32kdjO44ERPNsBgYhiPSj3Hr3jL2Ou+rCwqAvLHmPA4
      EuSGWD1PAgMBAAECggEAI3CaX9nraSf29OYC2AHvPGRfnrVGITR/rNe+q5sR1B4b
      oSZSIOwpPRf1wkPiYAoZzcQjjmYIIrT85IOj0cQXJ6emje4W1f88P5SbO4YLb54R
      H4GmUJxZlO7gd6FM++UvBn9NdZkzlHb8jZ6XFnrAU+LBO57CKOaDbELte2Mw4IKc
      rrVL7bY5eKVuk+ULLrbO0PpvLrLAk1IFSU36oxFtURj+ULnkS7xxgz7Oy+kbs+Vo
      djvyiXppox+x8Sb3wY+wfDaHK55RN+yb4TdWwgC7bkQ5QKX5RtRDYZjJDgj+Z0X1
      4H//xofwoysc/zHwmPhPb11MkMzAH2L/I0mOYUBpgQKBgQD0K5Im5ErawQvdeYTG
      ercqMY3POWf7fsPYVCokG6sW0o4Lu6P5WmI3rTDydq7W2plyqdZ83Kxw3gCkwAgp
      hBvadCyz/xP+BmWccd7R90Ma/IJUGKoSuRjkCo53FNLDfQksPEnHf8s1OdWVrXL7
      KURfzJRXz3LTimBmtc7ukAoAsQKBgQDMFfAYyxs+Hil9xIyuWPKCJFAMj0xrS7/B
      +PPvOneJiNGbE1aRcVqCgPczkg+ZKpN8Zn/knUMhWWGO75s1b8UHttQeMTDxgvEH
      CYso3QHeUKjvEH1oziOFvzgdrAAzNdM1HS8MIed9kiKyAg7W0zh0GERfFD+aeSRQ
      u6n27oWd/wKBgBBe43usDsC/9LWysg5EqAcyL1nXdXtNMoBMlE67dCshjtiGiiXr
      w24MNJ3tCyfonCUt8e2JNh6TI+Pn5CQ0cVGiPGUNEyAS+bkVgWT+eQdUKsDMrop2
      0o5njsm5IbBtr7HBkQjJLqyw5fsVGAJy79ykcMW6aO559qCsS+V+zszhAoGAYhYh
      ISls3HwOoP24R4tEcrwVJRQyPFdZwFZwlwfYr+dsJkYzExAR2is1pDmM+aZ24BE7
      Ypsayop00wfh5trjLYP3itNFnK28Pg+eLHOcFEdcCho4zAhXFk8DH2+tYO97pUlz
      dTdOVRHJTxiiHSnDNjj7k17d+tZCV/L6C040Ne0CgYAb7e7sZioparOW8raWIvy2
      a7ezYqlN8d/vrWzb9IAaGU1oC6ZwUekKFAEC5nT+tFohPkVPrQaY8offGsIyfN6N
      iFqihdMjHfijJBB1q7NV7czLZ1g1MB6vfCp5vDyJlkGbniesarKakDIGWejX8pyU
      ajz1pkuVmxeHRGwTRFcQuA==
      -----END PRIVATE KEY-----
    termination: edge
  to:
    kind: Service
    name: jenkins-master
    weight: 100
  wildcardPolicy: None