---

- name: Add Kubernetes.io apt key
  shell: "curl -sSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -"
  args:
    warn: no

- name: Add Kubernetes stable repository.
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main 
    state: present

- name: Update for Kubernetes repo
  apt:
    update_cache: yes

- name: Install a list of packages for kubernetes
  apt:
    pkg:
    - kubelet

- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Make sure a kubelet is running
  systemd:
    state: started
    name: kubelet

- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  shell: |
    swapoff -a

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- sysctl:
    name: vm.swappiness
    value: '0'
    state: present

- sysctl:
    name: vm.overcommit_memory
    value: '1'
    state: present

- sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present 

- name: Copy CA Certificates 
  copy:
    src: /Users/shaker/Documents/certs/ca.shaker242.crt 
    dest: /usr/local/share/ca-certificates/ca.shaker242.crt 
    owner: root
    group: root
    mode: '0644'

- name: Load CA Certificate 
  shell: /usr/sbin/update-ca-certificates

