apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations: null
  name: nfs-nobody
priority: 10
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
  ranges:
  - min: 5000
    max: 6000
groups:
- system:authenticated
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
runAsUser:
  type: MustRunAsRange
  uidRangeMin: 65534
  uidRangeMax: 65634
users: [] 
#  - service... 
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: MustRunAs 
  ranges:
  -  min: 50000
     max: 70000
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim